name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/EventBus/EventBus.csproj
    - name: Build
      run: dotnet build src/EventBus/EventBus.csproj --no-restore
    - name: Test
      run: dotnet test src/EventBus/EventBus.csproj --no-build --verbosity normal
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2
      with:
       PROJECT_FILE_PATH: src/EventBus/EventBus.csproj
       NUGET_KEY: ${{secrets.NUGET_API_KEY}}
